name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.3'

      - name: Build
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o client-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/client

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: client-${{ matrix.goos }}-${{ matrix.goarch }}
          path: client-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          path: .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            client-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
