name: Go package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.3

      - name: Linter-check
        run: go run github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.1 run

      - name: Build
        run: go build -o memento ./cmd/server/

      - name: Test
        run: go test -v ./...

      - name: Transfer
        uses: actions/upload-artifact@v3
        with:
          name: memento
          path: memento


  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: memento

      - name: Display structure of downloaded files
        run: ls -R

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: memento
          target: memento

  copy-serv-file:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy service file
        uses: appleboy/scp-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            source: memento.service
            target: /etc/systemd/system/

  copy-conf-file:
    runs-on: ubuntu-latest
    needs: [copy-serv-file]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add release date
        run:  sed -i '4a\  version':' '$(date +%Y%m%d%H%M%S)'' config.yml

      - name: Copy config file
        uses: appleboy/scp-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            source: config.yml
            target: ./memento/

  copy-migr-file:
    runs-on: ubuntu-latest
    needs: [copy-conf-file]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3    

      - name: Copy migration files
        uses: appleboy/scp-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            source: migrations/
            target: ./memento/

  restart-service:
    runs-on: ubuntu-latest
    needs: [copy-migr-file]
    steps:
      - name: Restarts the service
        uses: appleboy/ssh-action@v0.1.7
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            script: |
              chmod +x ./memento/memento && sudo systemctl daemon-reload && sudo systemctl restart memento.service && sudo systemctl status memento.service            
