name: Go package

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.3

      - name: Linter-check
        run: go run github.com/golangci/golangci-lint/cmd/golangci-lint@latest run
